name: Build and Deploy TODO App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Backend
      run: docker build -t todo-backend ./backend

    - name: Build Frontend
      run: docker build -t todo-frontend ./frontend
