---
- name: Automatisation de la sécurité des serveurs
  hosts: servers
  become: yes
  tasks:
    - include_tasks: tasks_install_openscap.yml
    - include_tasks: tasks_security_patch.yml
    - include_tasks: tasks_ssh_access.yml
    - include_tasks: tasks_vulnerability_scan.yml
